[project]
name = "deploy-mind-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.2",
    "markitdown[all]>=0.1.4",
    "psycopg2>=2.9.11",
    "pydantic-ai>=1.56.0",
    "pyjwt>=2.11.0",
    "sqlmodel>=0.0.32",
    "uvicorn>=0.40.0",
    "resend>=2.6.0",
    "python-dotenv>=1.2.1",
    "passlib[bcrypt]",
    "google-auth>=2.48.0",
]
[project.scripts]
dev = "uvicorn app.main:app --reload --app-dir src"
start = "uvicorn app.main:app --app-dir src"

